import { useEffect, useRef, useState } from "react";
import Chart from "chart.js/auto";
import * as XLSX from "xlsx";
import { saveAs } from "file-saver";
import jsPDF from "jspdf";
import "jspdf-autotable";
import autoTable from "jspdf-autotable";
import { fetchReportData } from "~/services/reportService";

const getCurrentYear = () => new Date().getFullYear();
const getCurrentMonth = () => new Date().getMonth() + 1;
const getCurrentQuarter = () => Math.floor(new Date().getMonth() / 3) + 1;

export default function Index() {
  const barRef = useRef(null);
  const lineRef = useRef(null);
  const pieRef = useRef(null);
  const User = JSON.parse(localStorage.getItem("user"));
  const fileName = `${User.userName}_dashboard_report_${new Date().toISOString().split("T")[0]}`;

  // Sử dụng filterType mới
  const [filterType, setFilterType] = useState("day");
  const [year, setYear] = useState(getCurrentYear());
  const [month, setMonth] = useState(getCurrentMonth());
  const [quarter, setQuarter] = useState(getCurrentQuarter());

  const [orderStats, setOrderStats] = useState([]);
  const [revenueStats, setRevenueStats] = useState([]);
  const [topProducts, setTopProducts] = useState([]);
  const [orderStatusCounts, setOrderStatusCounts] = useState({
    Pending: 0,
    Delivery: 0,
    Delivered: 0,
    Canceled: 0,
  });

  // Thêm state cho kiểu xem
  const [viewType, setViewType] = useState("day"); // "day", "month", "quarter", "year"
  const [selectedMonth, setSelectedMonth] = useState(getCurrentMonth());
  const [selectedDay, setSelectedDay] = useState("");
  const [selectedQuarter, setSelectedQuarter] = useState(1);

  useEffect(() => {
    if (viewType === "day") {
      if (selectedMonth && selectedDay) {
        setFilterType(`day-${selectedMonth}-${selectedDay}`);
        setMonth(selectedMonth);
        setQuarter(1);
      } else if (selectedMonth) {
        setFilterType(`day-${selectedMonth}`);
        setMonth(selectedMonth);
        setQuarter(1);
      } else {
        setFilterType("day");
        setMonth(getCurrentMonth());
        setQuarter(1);
      }
    } else if (viewType === "month") {
      setFilterType("month");
      setMonth(selectedMonth);
      setQuarter(1);
    } else if (viewType === "quarter") {
      setFilterType("quarter");
      setQuarter(selectedQuarter);
      setMonth(1);
    } else if (viewType === "year") {
      setFilterType("year");
      setMonth(1);
      setQuarter(1);
    }
  }, [viewType, selectedMonth, selectedDay, selectedQuarter]);

  useEffect(() => {
    const fetchStats = async () => {
      try {
        const data = await fetchReportData({ filterType, year, month, quarter });
        setOrderStats(data.orderStats);
        setRevenueStats(data.revenueStats);
        setTopProducts(data.topProducts);
        setOrderStatusCounts(data.statusCounts);
      } catch (err) {
        console.error("Error fetching dashboard data", err);
      }
    };
    fetchStats();
  }, [filterType, year, month, quarter]);

  // Export to Excel handler
  const handleExportExcel = () => {
    // Prepare data for each sheet
    const ordersSheet = [
      ["Label", ...orderStats.map((_, i) => i + 1)],
      ["Orders", ...orderStats],
    ];
    const revenueSheet = [
      ["Label", ...revenueStats.map((_, i) => i + 1)],
      ["Revenue", ...revenueStats],
    ];
    const productsSheet = [
      ["Product Name", "Sold"],
      ...topProducts.map(p => [p.name, p.sold]),
    ];

    // Create workbook and add sheets
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(ordersSheet), "Orders");
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(revenueSheet), "Revenue");
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(productsSheet), "Top Products");

    // Export
    const wbout = XLSX.write(wb, { bookType: "xlsx", type: "array" });
    saveAs(new Blob([wbout], { type: "application/octet-stream" }), `${fileName}.xlsx`);
  };

  // Export to PDF handler
  const handleExportPDF = () => {
    const doc = new jsPDF("p", "mm", "a4");
    const margin = 14;

    // Title & time
    doc.setFontSize(18);
    doc.setTextColor("#333");
    doc.text("TBN Store Statistics Report", margin, 16);

    const date = new Date().toLocaleString("en-US");
    doc.setFontSize(10);
    doc.setTextColor("#666");
    doc.text(`Generated at: ${date}`, margin, 22);
    doc.text(`Generated by: ${User?.firstName || "Unknown"} ${User?.lastName || "Unknown"} UserName: ${User?.userName || "Unknown"}`, margin, 28);


    // Orders Table
    doc.setFontSize(14);
    doc.setTextColor("#000");
    doc.text("Orders Statistics", margin, 34);
    autoTable(doc, {
      startY: 38,
      head: [["#", ...orderStats.map((_, i) => `${i + 1}`)]],
      body: [["Orders", ...orderStats]],
      theme: "striped",
      styles: { fontSize: 9, cellPadding: 2 },
      headStyles: { fillColor: [99, 102, 241], textColor: 255 },
    });

    // Revenue Table
    let revenueY = doc.lastAutoTable.finalY + 10; // Adjust Y position for next table
    doc.setTextColor("#000");
    doc.setFontSize(14);
    doc.text("Revenue Statistics", margin, revenueY);
    autoTable(doc, {
      startY: revenueY + 4,
      head: [["#", ...revenueStats.map((_, i) => `${i + 1}`)]],
      body: [["Revenue ($)", ...revenueStats]],
      theme: "striped",
      styles: { fontSize: 9, cellPadding: 2 },
      headStyles: { fillColor: [16, 185, 129], textColor: 255 },
    });

    // Top Products
    let productY = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(14);
    doc.text("Best-Selling Products", margin, productY);
    autoTable(doc, {
      startY: productY + 4,
      head: [["Product Name", "Sold"]],
      body: topProducts.map(p => [p.name, p.sold]),
      theme: "striped",
      styles: { fontSize: 9 },
      headStyles: { fillColor: [59, 130, 246], textColor: 255 },
    });

    // Total revenue
    let totalY = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(14);
    doc.setTextColor("#22c55e");
    doc.text(
      `Total Revenue: $${revenueStats.reduce((a, b) => a + b, 0).toLocaleString("en-US")}`,
      margin,
      totalY
    );

    // Bar chart
    if (barRef.current) {
      const img = barRef.current.toDataURL("image/png");
      doc.addPage();
      doc.setFontSize(16);
      doc.setTextColor("#000");
      doc.text("Orders Chart (Bar)", margin, 20);
      doc.addImage(img, "PNG", margin, 26, 180, 90);
    }
    // Line chart
    if (lineRef.current) {
      const img = lineRef.current.toDataURL("image/png");
      doc.addPage();
      doc.setFontSize(16);
      doc.setTextColor("#000");
      doc.text("Revenue Chart (Line)", margin, 20);
      doc.addImage(img, "PNG", margin, 26, 180, 90);
    }
    // Pie chart
    if (pieRef.current) {
      const img = pieRef.current.toDataURL("image/png");
      doc.addPage();
      doc.setFontSize(16);
      doc.setTextColor("#000");
      doc.text("Order Status Distribution (Pie)", margin, 20);
      doc.addImage(img, "PNG", margin, 26, 120, 120);
    }

    doc.save(`${fileName}.pdf`);
  };

  // Chart instances to destroy before re-render
  const chartInstances = useRef({});

  useEffect(() => {
    // Destroy old charts if exist
    Object.values(chartInstances.current).forEach(chart => chart?.destroy());

    // Bar chart
    if (barRef.current) {
      const index = 1;
      chartInstances.current.bar = new Chart(barRef.current, {
        type: "bar",
        data: {
          labels: orderStats.map((_, i) => `${i + 1}`),
          datasets: [{
            label: "Orders",
            data: orderStats,
            backgroundColor: "#6366f1",
          }],
        },
        options: {
          responsive: true,
          plugins: { legend: { display: false } },
          scales: {
            x: {
              ticks: {
                autoSkip: false,
                maxRotation: 0,
                minRotation: 0,
              },
            },
          },
        },
      });
    }

    // Line chart
    if (lineRef.current) {
      chartInstances.current.line = new Chart(lineRef.current, {
        type: "line",
        data: {
          labels: revenueStats.map((_, i) => `${i + 1}`),
          datasets: [{
            label: "Revenue",
            data: revenueStats,
            borderColor: "#22c55e",
            backgroundColor: "rgba(34,197,94,0.2)",
            fill: true,
          }],
        },
        options: {
          responsive: true,
          plugins: { legend: { display: false } },
          scales: {
            x: {
              ticks: {
                autoSkip: false,
                maxRotation: 0,
                minRotation: 0,
              },
            },
          },
        },
      });
    }

    // Pie chart
    if (pieRef.current) {
      chartInstances.current.pie = new Chart(pieRef.current, {
        type: "pie",
        data: {
          labels: ["Pending", "Delivery", "Delivered", "Canceled"],
          datasets: [{
            data: [
              orderStatusCounts.Pending,
              orderStatusCounts.Delivery,
              orderStatusCounts.Delivered,
              orderStatusCounts.Canceled,
            ],
            backgroundColor: [
              "#facc15", // yellow
              "#38bdf8", // sky
              "#22c55e", // green
              "#ef4444", // red
            ],
          }],
        },
        options: { responsive: true },
      });
    }

    // Cleanup
    return () => {
      Object.values(chartInstances.current).forEach(chart => chart?.destroy());
    };
  }, [orderStats, revenueStats, orderStatusCounts]);

  return (
    <>
      <h1 className="text-2xl font-bold mb-6">Dashboard</h1>
      <div className="flex gap-2 mb-4">
        <button
          onClick={handleExportExcel}
          className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded font-semibold shadow"
        >
          Export to Excel
        </button>
        <button
          onClick={handleExportPDF}
          className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded font-semibold shadow"
        >
          Export to PDF
        </button>
      </div>

      {/* Filter controls */}
      <div className="flex flex-wrap gap-4 mb-6">
        {/* Chọn kiểu xem */}
        <select
          value={viewType}
          onChange={e => setViewType(e.target.value)}
          className="border rounded px-3 py-2"
        >
          <option value="day">Xem theo ngày</option>
          <option value="month">Xem theo tháng</option>
          <option value="quarter">Xem theo quý</option>
          <option value="year">Xem theo năm</option>
        </select>
        {/* Chọn tháng (cho day, month) */}
        {(viewType === "day" || viewType === "month") && (
          <select
            value={selectedMonth}
            onChange={e => {
              setSelectedMonth(Number(e.target.value));
              setSelectedDay("");
            }}
            className="border rounded px-3 py-2"
          >
            {Array.from({ length: 12 }, (_, i) => (
              <option key={i + 1} value={i + 1}>Tháng {i + 1}</option>
            ))}
          </select>
        )}
        {/* Chọn ngày (chỉ khi xem theo ngày) */}
        {viewType === "day" && (
          <select
            value={selectedDay}
            onChange={e => setSelectedDay(e.target.value)}
            className="border rounded px-3 py-2"
            disabled={!selectedMonth}
          >
            <option value="">-- Chọn ngày (tuỳ chọn) --</option>
            {Array.from({ length: 31 }, (_, i) => (
              <option key={i + 1} value={i + 1}>Ngày {i + 1}</option>
            ))}
          </select>
        )}
        {/* Chọn quý (chỉ khi xem theo quý) */}
        {viewType === "quarter" && (
          <select
            value={selectedQuarter}
            onChange={e => setSelectedQuarter(Number(e.target.value))}
            className="border rounded px-3 py-2"
          >
            {[1, 2, 3, 4].map(q => (
              <option key={q} value={q}>Quý {q}</option>
            ))}
          </select>
        )}
        {/* Năm */}
        <input
          type="number"
          min="2000"
          max={getCurrentYear()}
          value={year}
          onChange={e => setYear(Number(e.target.value))}
          className="border rounded px-3 py-2"
          placeholder="Year"
        />
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="bg-white rounded-xl shadow p-4">
          <h2 className="font-semibold mb-2">Orders (Bar Chart)</h2>
          <canvas ref={barRef} height={250}></canvas>
        </div>
        <div className="bg-white rounded-xl shadow p-4">
          <h2 className="font-semibold mb-2">Revenue (Line Chart)</h2>
          <canvas ref={lineRef} height={250}></canvas>
        </div>
      </div>
      {/* Pie chart for order statuses */}
      <div className="bg-white rounded-xl shadow p-4 mt-8 max-w-md mx-auto">
        <h2 className="font-semibold mb-2">Order Status Distribution</h2>
        <canvas ref={pieRef} height={250}></canvas>
        <ul className="mt-4 space-y-1 text-sm">
          <li><span className="inline-block w-3 h-3 rounded-full bg-yellow-400 mr-2"></span>Pending: {orderStatusCounts.Pending}</li>
          <li><span className="inline-block w-3 h-3 rounded-full bg-sky-400 mr-2"></span>Delivery: {orderStatusCounts.Delivery}</li>
          <li><span className="inline-block w-3 h-3 rounded-full bg-green-500 mr-2"></span>Delivered: {orderStatusCounts.Delivered}</li>
          <li><span className="inline-block w-3 h-3 rounded-full bg-red-500 mr-2"></span>Canceled: {orderStatusCounts.Canceled}</li>
        </ul>
      </div>
      {/* Top products */}
      <div className="bg-white rounded-xl shadow p-4 mt-8">
        <h2 className="font-semibold mb-2">Best-Selling Products</h2>
        <ul>
          {topProducts.map((p, idx) => (
            <li key={idx} className="py-1 flex justify-between">
              <span>{p.name}</span>
              <span className="font-bold">{p.sold} sold</span>
            </li>
          ))}
        </ul>
      </div>
      {/* Revenue summary */}
      <div className="bg-white rounded-xl shadow p-4 mt-8">
        <h2 className="font-semibold mb-2">Total Revenue</h2>
        <div className="text-2xl font-bold text-green-600">
          ${revenueStats.reduce((a, b) => a + b, 0).toLocaleString("en-US")}
        </div>
      </div>
    </>
  );
}